spring:
  datasource:
    username: emarket_dev
    password: emarket@dev@-123
    url: jdbc:mysql://47.98.195.250:3306/emarket_dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      host: 47.98.195.250
      port: 27018
      username: oaWork
      password: n1DeC@@work
      database: nidcai-oa


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.nidecai.managerndc.entity

mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  notEmpty: true
  identity: MYSQL

pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#s howSql
logging:
  level:
    com:
      nidecai:
        managerndc:
           mapper : debug



